Attempt to upgrade to spring-security-auth0:0.3.
Application still fails to run with a similar error (java.lang.NoSuchMethodError: javax.servlet.ServletContext.addFilter(Ljava/lang/String;Ljavax/servlet/Filter;)Ljavax/servlet/FilterRegistration$Dynamic;)

Readme updated with new error log.